// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhxpzeyklqbkeibvreqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoeHB6ZXlrbHFia2VpYnZyZXF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyOTUzMjAsImV4cCI6MjA1MTg3MTMyMH0.nONDvevMQHY7sMQ0pEchemYQesr3HqyiP4ZTb_g7wX0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);